<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameTrainer.Core\GameTrainer.Core.csproj" />
    <ProjectReference Include="..\GameTrainer.Modules.CrimsonDesert\GameTrainer.Modules.CrimsonDesert.csproj" />
  </ItemGroup>
</Project>
